kursus/urls.py
from django.conf.urls import url

from .views import (
    MateriListView, 
    MateriDetailView,
    MateriKategoriListView,
    LoginView,
    LogoutView,
    MateriCreate,
    MateriManage,
    MateriDelete,
    MateriEdit,
    search,
)

app_name = 'mysite'
urlpatterns = [
    url('search/', search, name='search'),
    url('logout/',LogoutView, name="logout"),
    url('login/',LoginView, name="login"),
    url('delete/(?P<pk>\d+)', MateriDelete, name="delete"),
    url('edit/(?P<pk>\d+)', MateriEdit, name="edit"),
    url ('manage/', MateriManage, name='manage'),
    url('create/',MateriCreate, name='create'),
    url('kategori/(?P<kategori_input>[^/]+)',MateriKategoriListView.as_view(), name='kategori'),
    url('detail/(?P<pk>\d+)', MateriDetailView.as_view(), name="detail"),
    url('', MateriListView.as_view(), name="list"),  
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('kursus/', include('kursus.urls', namespace="kursus")),
    path('',index, name="index"),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = "ИРсМ Администратор"
admin.site.site_title = "ИРсМ Администратор Портал"
admin.site.index_title = "Добро пожаловать на исследовательский портал ИРсМ"

kursus/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
from ckeditor_uploader.fields import RichTextUploadingField

class Materi(models.Model):
    judul       = models.CharField(max_length=255, verbose_name="название")
    isi         = RichTextUploadingField( verbose_name="Содержимые")
    # isi         = models.TextField()
    kategori    = models.CharField(max_length=100, verbose_name = "категория")
    published   = models.DateTimeField(auto_now_add=True, verbose_name="Опубликование")
    update      = models.DateTimeField(auto_now=True, verbose_name="Обновить")
    penulis     = models.CharField(max_length=255, verbose_name="Автор")
    slug        = models.SlugField(blank=True, editable=False)

    class Meta :
        verbose_name_plural = "Статьи"

    def save(self):
        self.slug = slugify(self.judul)
        super().save()

     # related with CreateView, when saving  
    # # def get_absolute_url(self):
    #     return reverse("kursus:detail", kwargs={"pk": self.pk})
    

    # def __str__ (self):
    #     return "{}. {}". format(self.id, self.judul)  

     

kursus/forms.py
from django.forms import ModelForm
from django import forms
from .models import Materi

class MateriForm(ModelForm):
    class Meta :
        model = Materi
        fields = [
            'judul',
            'isi',
            'kategori',
            'penulis'
        ]
        # mengubah ukuran kolom input pada create.html
        widgets = {
            'judul' : forms.TextInput(attrs={'size':60}),
            'kategori' : forms.TextInput(attrs={'size':60}),
            'penulis': forms.TextInput(attrs={'size':60})
        }

kursus/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Materi
from .forms import MateriForm

from django.contrib.auth import authenticate, login, logout

#with template base view
from django.views.generic import ListView, DetailView

from django.db.models import Q

def search(request):
    # ini for cari samua judul
    queryMateri = Materi.objects.all()
   
    queryCariJudul = request.GET.get('kolomCari')
    # print(queryCariJudul) 

    # ini for pilih-pilih judul saja
    # if queryCariJudul != '' and queryCariJudul is not None :
    #     queryMateri = queryMateri.filter(judul__icontains =queryCariJudul) 
    if queryCariJudul != '' and queryCariJudul is not None :
            queryMateri = queryMateri.filter(Q(judul__icontains = queryCariJudul)| Q(penulis__icontains = queryCariJudul) | Q(kategori__icontains = queryCariJudul)).distinct() 
     
    # print(queryMateri) 

    context = {
        'page_title' : 'Search Materi', 
        'queryset' :  queryMateri
    }
    return render(request,"kursus/search.html", context)


def LoginView(request):
    context= {
        'page_title' : 'войдите',  
    }
    user = None
    if request.method == 'POST' :
        # print(request.POST)
        username_login = request.POST['username']
        password_login = request.POST['password']
        # print(username_login)
        # print (password_login)
        #melakukan authenticate dengan database
        user = authenticate(username = username_login, password = password_login)
        # print(user)
        # melakukan login
        # menampilkan tulisan user di halaman html
        if user is not None :
            login(request, user)
            return redirect('kursus:list')
        else  :
            return redirect('kursus:login')

    #membuat kondisi jika user telah login
    # dan iseng mengetik login di urlbar.. pretlah
    if request.method == 'GET':
        if request.user.is_authenticated:
            # logika untuk user
            return redirect('kursus:list')
        # else :
             # logika untuk anonymous
    return render (request,'kursus/login.html', context)

@login_required
def LogoutView(request):
    context ={
        'page_title' : 'Logout'
    }
    if request.method == 'POST' :
        # print(request.POST)
        if request.POST['Logout'] == 'Да':
            # print('Proses logout')
            logout(request)
        return redirect('kursus:list')

    return render (request, 'kursus/logout.html', context)
   
# class MateriDeleteView(DeleteView):
#     model = Materi
#     template_name = "kursus/Materi_confim_delete.html"
#     success_url = reverse_lazy('kursus:manage')

@login_required
def MateriDelete(request, pk):
    item = Materi.objects.filter(id=pk)
    # print(item)
    context = {
        'page_title' : 'подтверждения Удаления ',
        'item' : item,
    }
    if request.method == 'POST' :
        Materi.objects.filter(id=pk).delete()
        return redirect('kursus:manage')
    
    return render (request, 'kursus/Materi_confim_delete.html', context)
    


# class MateriEditView(UpdateView):
#     model = Materi
#     template_name = "kursus/Materi_manage_edit.html"
#     form_class = MateriForm

@login_required
def MateriEdit(request, pk):
    Materi_update = Materi.objects.get(id=pk)
    
    data = {
        'judul'   : Materi_update.judul,
        'isi'     : Materi_update.isi,
        'kategori': Materi_update.kategori 
    }
    Materi_form = MateriForm(request.POST or None, initial = data, instance=Materi_update)
    
    if request.method == 'POST' :
        if Materi_form.is_valid():
            Materi_form.save()
        return redirect ('kursus:list')

    context = {
        "page_title" : 'Обновлять Статья',
        "form" : Materi_form,
    }
    
    return render(request,"kursus/Materi_create.html", context)
    

# class MateriManageView(ListView):
#     model = Materi
#     template_name = "kursus/Materi_manage.html"
#     extra_context ={
#         'page_title' : 'Manage Materi'
#     }
#     ordering = ['-published']
@login_required
def MateriManage(request):
    daftar_materi = Materi.objects.all().order_by('-published')
    
    context ={
        'page_title' : 'Упавления статьи',
        'daftar_materi' : daftar_materi,
    }
    
    
    return render (request, "kursus/Materi_manage.html", context )

# class MateriCreateView(CreateView):
    # from .forms import MateriForm
    # form_class  = MateriForm
    # template_name = "kursus/Materi_create.html"
    # model = Materi
    # fields = [
    #         'judul',
    #         'isi',
    #         'kategori',
    #         'penulis'
    #     ]
    # extra_context = {
    #     'page_title' : 'Create Materi'
    # }

@login_required
def MateriCreate (request):
    form = MateriForm(request.POST or None)

    if request.method == 'POST' :
        if form.is_valid():
            form.save()
        return redirect ('kursus:list')

    context ={
        'page_title' : 'Создания Статьи ',
        'form' : form,
    }
    return render(request,'kursus/Materi_create.html', context)
    
    
    
class MateriDetailView(DetailView):
    model = Materi
    template_name = "kursus/Materi_detail.html"

    extra_context = {
        'page_title' : 'Детаил'
    }
    #Menampilkan pilihan kategori di sisi kiri
    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat= True).distinct()
        # print(kategori_list)
        self.kwargs.update({'kategori_list' : kategori_list}) 
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)



class MateriKategoriListView(ListView):
    model = Materi
    template_name = "kursus/Materi_kategori_list.html"
    ordering = ['-published']
 
    # menampilkan materi berdasarkan kategori
    def get_queryset(self):
        self.queryset = self.model.objects.filter(kategori = self.kwargs['kategori_input'])
        print(len(self.queryset))
        # print(self.kwargs)
        return super().get_queryset()

    #Menampilkan pilihan kategori di sisi kiri
    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat= True).distinct(). exclude(kategori= self.kwargs['kategori_input'])
       
        self.kwargs.update({'kategori_list' : kategori_list}) 
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

        
class MateriListView(ListView):
    # show all materi (object_list)
    model = Materi
    template_name = "kursus/Materi_list_anonymous.html"
    ordering = ['-published']
    # paginate_by = 2
    extra_context = {
        'page_title' : 'Списоков Статьи Materi',
    }

    #Menampilkan pilihan kategori di sisi kiri
    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat= True).distinct()
        
        self.kwargs.update({'kategori_list' : kategori_list}) 
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

kursus/templates/kursus/Materi_confim_delete.html
{% extends 'base_admin.html' %}

{% block page_title %}
        {{page_title}}    
{% endblock page_title %}  

{% block navbar %} 
        {% include 'snippets/navbar_staff.html' %}
{% endblock navbar %}

{% block content %}

<div class="container col-md-6" >
    <div class="alert alert-primary text-center mt-5" role="alert">
      <h4>  {{page_title}} </h4>
    </div>
      
    {% for hapus_item in item  %}
    <div class="text-center">
        <form method="POST">
            {% csrf_token %}
        
            <p> Материя : {{ hapus_item.judul }}</p>
            <p>категория : {{hapus_item.kategori}}</p>
                <p>Автор : {{hapus_item.penulis}}</p>
                <p>Опубликованный : {{hapus_item.published}}</p>
                <p>вы уверены, что хотите удалить ??? </p>
            
            <input class="btn btn-danger" type="submit" value="Подверждения">

            <a button class="btn btn-info" href="{% url 'kursus:manage' %}">Отмена</button> </a>
        </form>
    </div>
    {% endfor %}
</div>


{% endblock content %}

kursus/templates/kursus/Materi_create.html
{% extends 'base_admin.html' %}

{% block page_title %}
        {{page_title}}    
{% endblock page_title %}  

{% block navbar %} 
        {% include 'snippets/navbar_staff.html' %}
{% endblock navbar %}


{% block content %}
<div class="container">
    <div class="container">
        <div class="alert alert-primary text-center mt-5" role="alert">
         <h3> {{page_title}}</h3>
        </div>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <br>
        <input class="btn btn-primary" type="submit" value="Подтвержденный">
        
        <a button class="btn btn-danger" href="{% url 'kursus:manage' %}">Отмена</a>
    </form>
</div>
{% endblock content %}

kursus/templates/kursus/Materi_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{page_title}}    
{% endblock page_title %}
    
{% block navbar %} 
    {% if request.user.is_authenticated %} 
        {% include 'snippets/navbar_staff.html' %}
    {% else %} 
        {% include 'snippets/navbar_anonymous.html' %}
    {% endif %}
{% endblock navbar %}



{% block content %}
<div class="row">
  <!-- sisi kiri untuk kategori -->
  <div class="col-sm-3 mb-5">
      <!-- {{kategori_list}} -->
      <div class="list-group">
          <span class="list-group-item active">
            категория :
          </span>
          <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{% url 'kursus:list' %}"> Все категория 
            
          </a>
          {% for kategori in kategori_list %}

          <a href="{% url 'kursus:kategori' kategori %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
              {{kategori}}
              
          </a>
          {% endfor %}
        </div>  
  </div> 
  <!-- Akhir sisi kiri untuk kategori -->


   <!-- sisi kanan untuk isi materi -->
    <div class="col-sm-9">
            <div class="container"> 
              <div class="card ">
                  <div class="card-header">
                    <h3>  {{materi.judul}} </h3>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0 text-justify">
                      <p>{{materi.isi | safe}} </p>

                

                      <footer class="blockquote-footer">категория : {{materi.kategori}}
                        , <cite title="Source Title">автор : {{materi.penulis}}</cite>
                        , <cite title="Source Title">опубликованный : {{materi.published | date}}</cite>
                      , <cite title="Source Title">обновить : {{materi.update}}</cite>  
                      </footer>
                    </blockquote>

                  </div>
                </div>
            </div>
     </div>
</div>
{% endblock content %}
    

kursus/templates/kursus/Materi_kategori_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
{% block navbar %} 
    {% if request.user.is_authenticated %} 
        {% include 'snippets/navbar_staff.html' %}
    {% else %} 
        {% include 'snippets/navbar_anonymous.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
<div class="row">
        <!-- sisi kiri untuk kategori -->
        <div class="col-sm-3 mb-5">

            <!-- {{kategori_list}} -->
            <div class="list-group">
                <span class="list-group-item active">
                    категория :
                </span>
                <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{% url 'kursus:list' %}"> Все категория  
            </a>
                {% for kategori in kategori_list %}
                <a href="{% url 'kursus:kategori' kategori %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    {{kategori}}
                    
                </a>
                {% endfor %}
            </div>
        </div>
                

    
    <div class="col-sm-9">
    <!-- {{object_list}}     -->
            <div class="alert alert-primary mt-1 d-flex justify-content-between align-items-center " role="alert">
            <h4> категория : {{kategori_input}}  
            </h4>  
            </div>
            {% for materi in object_list %}
            <div class="card mb-3">
                <h5 class="card-header"><a href="{% url 'kursus:detail' materi.id %}">   {{materi.judul}} </a></h5>
                <div class="card-body">
                     <p class="card-text">{{materi.isi | safe | truncatewords:50}}</p>
                   <a href="{% url 'kursus:detail' materi.id %}" class="btn btn-primary">полностью</a>
                </div>
            </div> 
        </dir>
        
    {% endfor %}
</div>

{% endblock content %}
    

kursus/templates/kursus/Materi_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
{% block navbar %} 
    <h1>kokoksaasda</h1>
    {% include '/snippets/navbar_anonymous.html' %}
{% endblock navbar %}


{% block category %}
<!-- user Login -->
<p>Selamat Datang, {{user}}</p>
        <a href="{% url 'kursus:login' %}"><button>login</button></a>

        <a href="{% url 'kursus:logout' %}"><button>logout</button></a>

     <!-- {{kategori_list}} -->
    <div class="list-group mt-1">
        <span class="list-group-item active">
            категория :
        </span>
        {% for kategori in kategori_list %}
        <a href="{% url 'kursus:kategori' kategori %}" class="list-group-item list-group-item-action">
            {{kategori}}
        </a>
        {% endfor %}
      </div>

      tes
        
{% endblock category %}
    
{% block content %}


    <!-- {{object_list}}     -->
    {% for materi in object_list %}
    <div class="card">
    <h5 class="card-header"><a href="{% url 'kursus:detail' materi.id %}">   {{materi.judul}} </a></h5>
    <div class="card-body">
      <!-- <h5 class="card-title">Special title treatment</h5> -->
      <p class="card-text">{{materi.isi | safe | truncatewords:50}}</p>
      <a href="{% url 'kursus:detail' materi.id %}" class="btn btn-primary">полностью</a>
    </div>

</div>  
<br> 
    {% endfor %}  

  
{% endblock content %}
    

kursus/templates/kursus/Materi_list_anonymous.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
{% block navbar %} 
    {% if request.user.is_authenticated %} 
        {% include 'snippets/navbar_staff.html' %}
    {% else %} 
        {% include 'snippets/navbar_anonymous.html' %}
    {% endif %}
{% endblock navbar %}

    
{% block content %}
<div class="row">
    <!-- sisi kiri untuk kategori -->
    <div class="col-sm-3 mb-5">
          <!-- {{kategori_list}} -->
     <div class="list-group mt-1">
        <span class="list-group-item active">
            категория :
        </span>
        {% for kategori in kategori_list %}
        <a href="{% url 'kursus:kategori' kategori %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            {{kategori}}
            <!-- <span class="badge badge-light badge-pill">0    
            </span> -->
        </a>
        {% endfor %}    
       
    </div>
    </div>
    <!-- Akhir sisi kiri untuk kategori -->

    <!-- sisi kanan untuk isi materi -->
    <div class="col-sm-9">
                <!-- {{object_list}}     -->
        {% for materi in object_list %}
        <div class="card bg-light mt-2">
            <h5 class="card-header  bg-light"><a href="{% url 'kursus:detail' materi.id %}">   {{materi.judul}} </a></h5>
            <div class="card-body">
                 <!-- <h5 class="card-title">Special title treatment</h5> -->
                <p class="card-text text-justify">{{materi.isi | safe | truncatewords:50}}</p>
                <a href="{% url 'kursus:detail' materi.id %}" class="btn btn-info btn-sm">полностью</a>
            </div>
         </div>  
        <br> 
    {% endfor %}  
    </div>
    <!-- akhir sisi kanan untuk isi materi -->
</div>

 
{% endblock content %}
    

kursus/templates/kursus/Materi_manage.html
{% extends 'base_admin.html' %}


{% block page_title %}
    {{page_title}}
{% endblock page_title %}

{% block navbar %} 
        {% include 'snippets/navbar_staff.html' %}
{% endblock navbar %}


{% block content %}

<a class="btn btn-primary btn-block mb-2" href="{% url 'kursus:create' %}" role="button">Создать Статья </a>

<!-- {{object_list}} -->
<table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Но.</th>
        <th scope="col">Название</th>
        <th scope="col">Категория</th>
        <th scope="col">Автор</th>
        <th scope="col">Настройки</th>
      </tr>
    </thead>
    <tbody>
      
  {% for list_materi in daftar_materi %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{list_materi.judul}}</td>
        <td>{{list_materi.kategori}}</td>
        <td>{{list_materi.penulis}}</td>
        <td>   
            <a href="{% url 'kursus:delete' list_materi.id  %}"> <button type="button" class="btn btn-sm btn-outline-danger mb-1 mt-1">Удалять</button></a>

            <a href="{% url 'kursus:edit' list_materi.id %}">
            <button type="button" class="btn btn-sm btn-outline-info">Cмена</button></a>
        </td>
      </tr>
  {% endfor %}
  
 
    
  
    </tbody>
  </table>
  
  
{% endblock content %}
    
    

    

kursus/templates/kursus/Materi_manage_edit.html
{% extends 'base_admin.html' %}

{% block page_title %}
        {{page_title}}    
{% endblock page_title %}  

{% block navbar %} 
        {% include 'snippets/navbar_staff.html' %}
{% endblock navbar %}

{% block content %}

<div class="container" >
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <br>
        <input class="btn btn-primary" type="submit" value="Подтверждения">

        <a button class="btn btn-danger" href="{% url 'kursus:manage' %}">Отмена</button> </a>

    </form>
</div>
{% endblock content %}

kursus/templates/kursus/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>login</title>
</head>
<body>
    <div class="container col-md-6">
      <div class="alert alert-primary text-center mt-5" role="alert">
       <h4> {{page_title}} </h4>
      </div>
      
    <form method="POST">
        {% csrf_token %}
        <div class="form-group mt-4">
          <label for="username">Имя Ползователья  </label>
          <input type="text" class="form-control" id="username" name="username" placeholder="">
          <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
        </div>
        <div class="form-group">
          <label for="password">Пароль</label>
          <input type="password" class="form-control" id="password" name="password" placeholder="">
        </div>

        <div class="text-center">
            <button type="submit" class=" btn btn-primary btn-sm">Отправить</button>
            <a href="{% url 'kursus:list' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Отмена</a>
        </div
    </form>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>



    <!-- <h1>{{page_title}}</h1>
   
    <form action="" method="POST">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" id="username">
        <br><br>
        <label for="password">Password</label>  
        <input type="password" name="password" id="password">
        <br><br>
        <button type="submit">LOGIN</button> 
        <a href="{% url 'kursus:list' %}">Cancel</a>

    </form> -->




      

kursus/templates/kursus/search.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{page_title}}
{% endblock page_title %}
    
{% block navbar %} 
    {% if request.user.is_authenticated %} 
        {% include 'snippets/navbar_staff.html' %}
    {% else %} 
        {% include 'snippets/navbar_anonymous.html' %}
    {% endif %}
{% endblock navbar %}

    
{% block content %}
<div class="container-fluid">
<form method="GET">
    <div class="form-group">
      <input type="text" name = 'kolomCari' id="kolomCari" class="form-control" placeholder="Найдётся всё. Например, название, категория или автор

      ">
    </div>
    </div>
    <button type="submit" class="btn btn-block btn-primary">Найти</button>
  </fieldset>
</form>



<!-- <div class="row">
    <!-- sisi kiri untuk kategori -->
    <!-- <div class="col-sm-3 mb-5"> -->
          <!-- {{kategori_list}} -->
     <!-- <div class="list-group mt-1">
        <span class="list-group-item active">
            категория :
        </span>
        {% for kategori in kategori_list %}
        <a href="{% url 'kursus:kategori' kategori %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            {{kategori}} -->
            <!-- <span class="badge badge-light badge-pill">0    
            </span> -->
        <!-- </a>
        {% endfor %}    
       
    </div> -->
    <!-- </div> -->
    <!-- Akhir sisi kiri untuk kategori -->

    <!-- sisi kanan untuk isi materi -->
    <!-- <div class="col-sm-9"> -->
                <!-- {{object_list}}     -->
        {% for materi in queryset %}
        <div class="card bg-light mt-2">
            <h5 class="card-header  bg-light"><a href="{% url 'kursus:detail' materi.id %}">   {{materi.judul}} </a></h5>
            <div class="card-body">  
                <p class="card-text">{{materi.isi | safe | truncatewords:50}}</p>
                <p class="card-text"><small class="text-muted">категория : {{materi.kategori}} 
                    - автор : {{materi.penulis}} - опубликованый : {{materi.published|date}}</small></p>
                <a href="{% url 'kursus:detail' materi.id %}" class="btn btn-primary">полностью</a>
                
            </div>
         </div>  
        <br> 
    {% endfor %}  
    </div>
    <!-- akhir sisi kanan untuk isi materi -->
</div>

</div>
{% endblock content %}
    