kursus/urls.py
from django.conf.urls import url

from .views import (
    MateriListView, 
    MateriDetailView,
    MateriKategoriListView,
    LoginView,
    LogoutView,
    MateriCreate,
    MateriManage,
    MateriDelete,
    MateriEdit,
    search,
)

app_name = 'mysite'
urlpatterns = [
    url('search/', search, name='search'),
    url('logout/',LogoutView, name="logout"),
    url('login/',LoginView, name="login"),
    url('delete/(?P<pk>\d+)', MateriDelete, name="delete"),
    url('edit/(?P<pk>\d+)', MateriEdit, name="edit"),
    url ('manage/', MateriManage, name='manage'),
    url('create/',MateriCreate, name='create'),
    url('kategori/(?P<kategori_input>[^/]+)',MateriKategoriListView.as_view(), name='kategori'),
    url('detail/(?P<pk>\d+)', MateriDetailView.as_view(), name="detail"),
    url('', MateriListView.as_view(), name="list"),  
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('kursus/', include('kursus.urls', namespace="kursus")),
    path('',index, name="index"),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.site.site_header = "ИРсМ Администратор"
admin.site.site_title = "ИРсМ Администратор Портал"
admin.site.index_title = "Добро пожаловать на исследовательский портал ИРсМ"

templates/snippets/navbar_anonymous.html
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'kursus:list'  %}">Электронное обучение</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">О ИРСМ<span class="sr-only">(current)</span></a>
             </li>
             <!-- <li class="nav-link active">
              time :  
             {{now}}
            </li> -->
            <!-- <li class="nav-item">
              <a class="nav-link" href="/admin" tabindex="-1" aria-disabled="true">Admin</a>
            </li> -->
          </ul>
          <div>
              <ul class="navbar-nav mr-sm-5">
                <li class="nav-link active">
                    Добро пожаловать, посетитель
                    <a button class="btn btn-sm btn-outline-primary" type="submit" href="{% url 'kursus:login' %}">Войти</a button>
                </li>
              </ul>
          </div>

          <a href="{% url 'kursus:search' %}"><i class="fa fa-search" style="font-size:30px;color:lightblue;text-shadow:2px 2px 4px #000000;"></i></a>

          <!-- <form action="" method="GET" class="form-inline my-2 my-sm-0">
            <input class="form-control mr-sm-2" type="search" placeholder="поиск" aria-label="Search">

            <button class="btn btn-sm btn-outline-success my-2 my-sm-0" type="submit">поиск</button>
          </form> -->

      



        </div>
      </nav>

templates/snippets/navbar_staff.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'kursus:list'  %}">Электронное обучение</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">О ИРСМ<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'kursus:create' %}">Создание </a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'kursus:manage' %}">Упавления </a>
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Admin
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'kursus:create' %}">Create</a>
            <a class="dropdown-item" href="{% url 'kursus:manage' %}">Manage </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link" href="/admin" tabindex="-1" aria-disabled="true">Admin</a>
        </li> -->
      </ul>
        <div>
          <ul class="navbar-nav mr-sm-5">
            <li class="nav-link active">
                Добро пожаловать, {{user.username }}
                <a button class="btn btn-sm btn-outline-primary" type="submit" href="{% url 'kursus:logout' %}">Выйти</a button>
            </li>
          </ul>
      </div>
      <a href="{% url 'kursus:search' %}"><i class="fa fa-search" style="font-size:30px;color:lightblue;text-shadow:2px 2px 4px #000000;"></i></a>

      
    </div>
  </nav>

templates/snippets/navbar_user.html
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'kursus:list' %}">E-Learning</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'kursus:create' %}">Create</a>
                <a class="dropdown-item" href="{% url 'kursus:manage' %}">Manage </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="/admin" tabindex="-1" aria-disabled="true">Admin</a>
            </li> -->
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>